# Секция "services" запускает список нужных нам программ (контейнеров)
services:

  # Это внутреннее имя нашей программы внутри Docker (название для системы)
  freetakserver:
  
    # Откуда скачивать программу. Качаем свежий FreeTAKServer с официального GitHub
    image: ghcr.io/freetakteam/freetakserver:latest
    
    # Как контейнер будет красиво называться в списке запущенных процессов вашего ПК
    container_name: freetakserver
    
    # Секция "ports" открывает двери (порты) из контейнера на ваш реальный компьютер
    ports:
      # Открываем порт 8080 для веб-меню и внутренних системных запросов (API)
      - "8080:8080"
      
      # Открываем порт 8443 для того же веб-меню, но с защитой шифрования (SSL)
      - "8443:8443"
      
      # ГЛАВНЫЙ ПОРТ: Сюда в приложении ATAK на телефоне подключаемся без шифрования
      - "8087:8087"
      
      # ВТОРОЙ ПОРТ: Сюда подключаемся в ATAK, если внутри приложения включили SSL-защиту
      - "8089:8089"
      
    # Секция "environment" задает внутренние настройки для самого сервера
    environment:
      # FTS_CONNECTION_MESSAGE — команда серверу заменить дефолтное приветствие на ваш текст
      - FTS_CONNECTION_MESSAGE="Добро пожаловать в систему VALHALLA, Оператор!"
      
    # Секция "volumes" привязывает виртуальную папку контейнера к жесткому диску вашего ПК
    volumes:
      # fts-data (папка на ПК) связывается с /app/FreeTAKServer (папка внутри контейнера)
      # Это нужно, чтобы при перезапуске сервера ваши карты и SSL-сертификаты не стирались
      - fts-data:/app/FreeTAKServer
      
    # Если сервер заглючит и упадет или вы перезагрузите компьютер — Docker включит его сам
    restart: always

# Секция "volumes" в самом низу регистрирует виртуальный диск в системе Docker
volumes:
  # Даем системе команду: "Создай на жестком диске постоянное место с именем fts-data"
  fts-data:
